language: go

go:
 - tip

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go test -covermode=count -coverprofile=profile.cov ./teamweek

after_success:
  - goveralls -v -service=travis-ci
